language: python
python:
  - 2.7
install:
  - pip install Django>=1.4 python-twitter>=0.8.7 factory_boy coveralls
  - python example/manage.py syncdb --noinput
script:
  - coverage run --source=twitterflux runtests.py
after_success:
  - coveralls